### ISSUE TITLE
Calcular metricas iniciales

### ISSUE THREAD

**Issue by gabrielaggp** [escasanova/HPIG2#3]
1. Optimización de Inventarios
Rotación de Inventarios: Calcular la rotación (ventas promedio / inventario promedio).
Días de Inventario Disponible: (Inventario promedio / costo de ventas diario).
Productos de Alta o Baja Rotación: Identificar los productos con las mayores y menores tasas de rotación.
2. Desempeño de Ventas
Ingresos Totales por Producto: Sumatoria de ventas por producto.
Top 10 Productos Más Vendidos: Basado en ingresos o unidades vendidas.
Ingresos por Proveedor: Total de ventas relacionadas con productos de cada proveedor.
3. Costos y Rentabilidad
Margen Bruto por Producto: (Ingresos - Costo) / Ingresos.
Costo Total de Adquisición: Sumatoria de costos en la tabla Purchases y PurchasePrices.
4. Previsión y Tendencias
Variación Mensual en Ventas: Comparar ingresos o unidades vendidas entre meses.
Productos Estacionales: Identificar patrones de alta demanda en ciertos periodos.
5. Eficiencia Operativa
Eficiencia de Proveedores: Tiempo promedio entre la orden de compra y la entrega (InvoicePurchases).
Desabastecimientos: Identificar productos con ventas superiores al inventario final.
6. Satisfacción del Cliente
Disponibilidad del Producto: Comparar ventas esperadas con inventario disponible (BegInventory y EndInventory).

**Comment by DFChica** [comment]
Las métricas ya mencionadas son muy completas y cubren diversos aspectos clave de la gestión de inventarios, desempeño de ventas, costos, rentabilidad, previsión, eficiencia operativa y satisfacción del cliente. Sin embargo, se podrían agregar otras métricas adicionales para profundizar el análisis y optimizar la toma de decisiones. A continuación las detallamos y cómo calcularlas:

## Optimización de Inventarios

1. Costo del Inventario Promedio
* Cálculo: (Inventario inicial + Inventario final) / 2 * Precio unitario promedio.
* Uso: Identificar costos asociados al mantenimiento del inventario.
* Consulta SQL:

SELECT
     AVG(onHand * Price) AS CostoPromedioInventario
FROM begInventory
WHERE startDate BETWEEN ‘YYYY-MM-DD’ AND ‘YYYY-MM-DD’;

2. Cobertura de Inventario
* Cálculo: (Inventario final / Ventas promedio diarias).
* Uso: Determinar cuántos días el inventario puede cubrir la demanda actual.

## Desempeño de Ventas

1. Contribución al Ingreso por Categoría o Clasificación
* Cálculo: (Ingresos de una categoría / Ingresos totales) * 100.
* Uso: Identificar qué categorías contribuyen más al total de ventas.
* Consulta SQL

SELECT
     Classification,
     SUM(SalesDollars) AS TotalIngresos,
     (SUM(SalesDollars) * 100.0 / (SELECT SUM(SalesDollars) FROM sales)) AS Contribucion
FROM sales
GROUP BY Classification
ORDER BY TotalIngresos DESC;

2. Velocidad de Ventas
* Cálculo: (Unidades vendidas / Días desde el inicio del periodo).
* Uso: Monitorear qué tan rápido se están moviendo los productos.

## Previsión y Tendencias

1. Tendencia de Crecimiento de Ventas
* Cálculo: ((Ventas del mes actual - Ventas del mes anterior) / Ventas del mes anterior) * 100.
* Uso: Evaluar si las ventas están creciendo o disminuyendo en el tiempo.
* Consulta SQL:
SELECT
     MONTH(SalesDate) AS Mes,
     SUM(SalesDollars) AS TotalVentas,
     LAG(SUM(SalesDollars)) OVER (ORDER BY MONTH(SalesDate)) AS VentasPrevias,
     ((SUM(SalesDollars) - LAG(SUM(SalesDollars)) OVER (ORDER BY MONTH(SalesDate))) * 100.0 /
     LAG(SUM(SalesDollars)) OVER (ORDER BY MONTH(SalesDate))) AS Tendencia
FROM sales
GROUP BY MONTH(SalesDate);

2. Predicción de Ventas (Técnica Avanzada)
* Cálculo: Usar métodos como regresión lineal o modelos ARIMA en Python para proyectar las ventas futuras.

from statsmodels.tsa.arima.model import ARIMA
import pandas as pd

Datos de ventas mensuales
data = pd.read_csv(‘sales.csv’, parse_dates=[‘SalesDate’])
monthly_sales = data.groupby(data[‘SalesDate’].dt.to_period(‘M’)).sum()

Modelo ARIMA
model = ARIMA(monthly_sales[‘SalesDollars’], order=(1,1,1))
results = model.fit()
print(results.forecast(steps=12)) # Proyección de ventas para 12 meses

## Eficiencia Operativa

1. Ciclo de Flujo de Efectivo
* Cálculo: Días de inventario + Días de cuentas por cobrar - Días de cuentas por pagar.
* Uso: Analizar cuánto tiempo toma convertir las inversiones en inventarios en efectivo.

2. Porcentaje de Entregas Puntuales por Proveedor
* Cálculo: (Entregas puntuales / Total entregas) * 100.
* Uso: Medir la confiabilidad de los proveedores.

## Satisfacción del Cliente

1. Tasa de Cumplimiento de Pedidos
* Cálculo: (Órdenes completas / Órdenes totales) * 100.
* Uso: Evaluar si se están cumpliendo las expectativas de los clientes.
* Consulta SQL:
SELECT
     (SUM(CASE WHEN SalesQuantity <= onHand THEN 1 ELSE 0 END) * 100.0 / COUNT(*)) AS TasaCumplimiento
FROM sales
JOIN begInventory ON sales.InventoryId = begInventory.InventoryId;
